server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    defaultPropertyInclusion: NON_EMPTY
  datasource:
    name: permission
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/permission?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: root
        login-password: root
    redis:
      host: 127.0.0.1
      port: 6379
      #password: root
      # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
      database: 0
      timeout: 3000s
      # 连接池配置，2.0中使用lettuce配置连接池
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认8
          max-active: 500
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: 50
          # 连接池中的最大空闲连接 （使用负值表示没有限制）默认8
          max-idle: 10
          # 最大活跃连接数（使用负值表示没有限制）
          min-idle: 500

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
  config: classpath:logback-spring.xml

log:
  path: logs
  level: debug
  name: permission
